### ISSUE TITLE
Gitlab ~8.14

### ISSUE THREAD

**Issue by sadortun** [nonplus/mantis2gitlab#2]
Hi @nonplus 

Have you re-tested your plugin with 8.* versions of gitlab ? 

Thanks,
Samuel

**Comment by nonplus** [comment]
I have not.  I wrote this script to do a one-time migration of my issues from Mantis to Gitlab and haven't touched it since, so I don't know how the API changed/evolved since then.  Possibly the script still works as is or could be tweaked to take advantage of new APIs.

FWIW, I've been happily using GitLab since October 2015.
